using System;

namespace OpenTK
{
	// Token: 0x02000050 RID: 80
	[AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
	public sealed class AutoGeneratedAttribute : Attribute
	{
		// Token: 0x04000156 RID: 342
		public string Category;

		// Token: 0x04000157 RID: 343
		public string Version;

		// Token: 0x04000158 RID: 344
		public string EntryPoint;
	}
}
